### PR TITLE
Infolabels: Name of the TV show corrected

### PR DESCRIPTION
**Pull request by Maven85**

### CODE REVIEW

**Comment by fayer3** [comment]
Hi, thanks for the fix, but why the 'html_parser.unescape'?

**Comment by Maven85** [comment]
Hi. Because TV shows contain HTML entities in the title, e.g. "Grey&apos;s Anatomy".

**Comment by fayer3** [comment]
thanks, will bi in the next release

**Comment by fayer3** [comment]
hi, I changed the html parser from the six package to the original python package, because I had problems with the six package on libreELEC. (might have been a temporary issue, because it worked after a restart, but I will keep the change.)

**Comment by Maven85** [comment]
hi. ok :)

**Pull request merged**
